from setuptools import setup

setup(name='pypol_',
      version='0.3',
      test_suite='nose.collector',
      description='Python polynomial library',
      author='Michele Lacchia',
      author_email='michelelacchia@gmail.com',
      license='GNU GPL v3',
      url='http://pypol.altervista.org/',
      download_url='http://github.com/rubik/pypol/downloads/',
      packages=['pypol'],
      package_dir={'pypol': 'src/pypol'},
      setup_requires=['nose>=0.11'],
      classifiers=['Topic :: Scientific/Engineering :: Mathematics',
                   'Intended Audience :: Science/Research',
                   'License :: OSI Approved :: GNU General Public License (GPL)',
                   'Natural Language :: English',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python :: 2.6',
                   ],
      )